# <a id='toc1_'></a>[Analyze and Prepare data using Python](#toc0_)

Lesson: 02

Time: 00:00:00

**Table of contents**<a id='toc0_'></a>    
- [Analyze and Prepare data using Python](#toc1_)    
  - [NumPy](#toc1_1_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

---

## <a id='toc1_1_'></a>[NumPy](#toc0_)

In [4]:
import numpy as np

A array of given shape and type, filled with `fill_value`:

In [6]:
np.full(shape=(2,3), fill_value=6)

array([[6, 6, 6],
       [6, 6, 6]])

Identity matrix/array:

In [7]:
np.identity(n=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Change typing:

In [13]:
x = np.array([1.0, 3.2, 0.8, 4.0, 7.98])
print(x)
print(x.astype(np.int64))

[1.   3.2  0.8  4.   7.98]
[1 3 0 4 7]


In [14]:
y = np.array([1, 3, 0, 4, 7])
print(y)
print(y.astype(np.float64))

[1 3 0 4 7]
[1. 3. 0. 4. 7.]


_Slice_ and _change_ the original array value:

In [22]:
arr = np.arange(10)
print(arr)  # The original values of arr

x = arr[2:6]
print(x)

x[1] = 17
print(x)
print(arr)  # The values of the array after Slicing and changing the value

x[:] = 64
print(x)
print(arr)  # The values of the array after Slicing and changing the value

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[ 2 17  4  5]
[ 0  1  2 17  4  5  6  7  8  9]
[64 64 64 64]
[ 0  1 64 64 64 64  6  7  8  9]


But use the `copy()`:

In [23]:
arr = np.arange(10)
print(arr)  # The original values of arr

x = arr[2:6].copy()
print(x)

x[1] = 17
print(x)
print(arr)  # The values of the array after Slicing and changing the value

x[:] = 64
print(x)
print(arr)  # The values of the array after Slicing and changing the value

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[ 2 17  4  5]
[0 1 2 3 4 5 6 7 8 9]
[64 64 64 64]
[0 1 2 3 4 5 6 7 8 9]
